"""add status and order to Task

Revision ID: 3f7d864b41c7
Revises: 10c312d6a852
Create Date: 2025-06-11 01:51:53.732090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f7d864b41c7'
down_revision = '10c312d6a852'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))

    # Step 2: Populate default values
    op.execute("UPDATE task SET status = 'todo' WHERE status IS NULL")
    op.execute("UPDATE task SET \"order\" = 0 WHERE \"order\" IS NULL")

    # Step 3: Alter to NOT NULL
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('status', nullable=False)
        batch_op.alter_column('order', nullable=False)
        
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('order')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
